version: "3.8"
services:
  mhconfig:
    image: mhconfig
    restart: always
    env_file: config.env
    networks:
      - mh
    volumes: 
      - ./data/config:/etc/memehub
  mhlogger:
    image: mhlogger
    restart: always
    networks: 
      - mh
    depends_on: 
      - mhconfig
  mhpermissions:
    image: mhpermissions
    restart: always
    networks:
      - mh
    depends_on:
      - mhconfig
networks:
  mh:
    name: mh
    driver: bridge