version: "3.8"
services:
  config:
    image: leifb/memehub-config
    restart: always
    env_file: config.env
    networks:
      - mh
    volumes: 
      - ./data/config:/etc/memehub
  logger:
    image: leifb/memehub-logger
    restart: always
    env_file: config.env
    networks: 
      - mh
    depends_on: 
      - config
  permissions:
    image: leifb/memehub-permissions
    restart: always
    env_file: config.env
    networks:
      - mh
    depends_on:
      - config
      - logger
  categories:
    image: leifb/memehub-categories
    restart: always
    env_file: config.env
    networks:
      - mh
    depends_on: 
      - config
      - logger
  limits:
    image: leifb/memehub-limits
    restart: always
    env_file: config.env
    networks: 
      - mh
    depends_on: 
      - config
      - logger
  contests:
    image: leifb/memehub-contests
    restart: always
    env_file: config.env
    networks: 
      - mh
    depends_on: 
      - config
      - logger
  bot:
    image: leifb/memehub-bot
    restart: always
    env_file: config.env
    networks: 
      - mh
    depends_on: 
      - config
      - logger
      - contests
      - limits
      - categories
      - permissions
  media_server:
    image: leifb/memehub-media-server
    restart: always
    env_file: config.env
    networks: 
      - mh
    depends_on: 
      - config
    ports:
      - "3344:3344"
networks:
  mh:
    name: mh
    driver: bridge