version: "3.8"
services:
  config:
    image: memehub-config
    restart: always
    env_file: config.env
    networks:
      - mh
    volumes: 
      - ./data/config:/etc/memehub
  logger:
    image: memehub-logger
    restart: always
    networks: 
      - mh
    depends_on: 
      - config
  permissions:
    image: memehub-permissions
    restart: always
    networks:
      - mh
    depends_on:
      - config
      - logger
  categories:
    image: memehub-categories
    restart: always
    networks:
      - mh
    depends_on: 
      - config
      - logger
  limits:
    image: memehub-limits
    restart: always
    networks: 
      - mh
    depends_on: 
      - config
      - logger
  contests:
    image: memehub-contests
    restart: always
    networks: 
      - mh
    depends_on: 
      - config
      - logger
  bot:
    image: memehub-bot
    restart: always
    networks: 
      - mh
    depends_on: 
      - config
      - logger
      - contests
      - limits
      - categories
      - permissions
networks:
  mh:
    name: mh
    driver: bridge