version: "3.8"
services:
  mhredis:
    image: bitnami/redis:6.0
    restart: always
    networks:
      - mh
    environment: 
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_AOF_ENABLED: "no"
    volumes:
      - ./data/redis:/bitnami/redis/data
  mhredis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    networks: 
      - mh
    environment:
      - REDIS_HOSTS=mhredis
    ports:
      - "8081:8081"
  mhmongo:
    image: mongo:4.4
    restart: always
    networks: 
      - mh
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mhmongo-mongoclient:
    image: mongoclient/mongoclient
    restart: always
    networks: 
      - mh
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://root:root@mhmongo
    ports:
      - "8082:3000"
networks:
  mh:
    name: mh
    driver: bridge